# This installs a shim into your ~/.chef/plugins/knife

require 'fileutils'

user_plugin_dir = File.expand_path("~/.chef/plugins/knife")
loader_path = File.expand_path("../loader", __FILE__)

FileUtils.mkdir_p(user_plugin_dir)
File.open(File.join(user_plugin_dir, "knife-boxer-shim.rb"), "w+") do |f|
  f.puts(<<-E)
# This is a shim to load knife-boxer from a git clone.
# this file is autogenerated by knife-boxer's install.rb script.
#
# If you wish to uninstall knife-boxer, you should also delete this
# file.
require "#{loader_path}"
E
end
